name: release
on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        wasi_sdk_version:
        - major: 11
          minor: 0

    name: Build release assets

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install SwiftWasm
      run: |
        sudo apt-get install \
          binutils \
          git \
          gnupg2 \
          libc6-dev \
          libcurl4 \
          libedit2 \
          libgcc-9-dev \
          libpython2.7 \
          libsqlite3-0 \
          libstdc++-9-dev \
          libxml2 \
          libz3-dev \
          pkg-config \
          tzdata \
          zlib1g-dev
        wget https://github.com/swiftwasm/swift/releases/download/swift-wasm-5.3.0-RELEASE/swift-wasm-5.3.0-RELEASE-ubuntu20.04_x86_64.tar.gz
        sudo tar zxvf swift-wasm-5.3.0-RELEASE-ubuntu20.04_x86_64.tar.gz --directory / --strip-components=1
        sudo chmod -R o+r /usr/lib/swift

    - name: Set the release version (tag)
      if: startsWith(github.ref, 'refs/tags/v')
      shell: bash
      run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Set the release version (main)
      if: github.ref == 'refs/heads/main'
      shell: bash
      run: echo "RELEASE_VERSION=canary" >> $GITHUB_ENV

    - name: Build release
      run: SWIFTC=/usr/bin/swift make build

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: <%= moduleName %>.wasm
        path: ./<%= moduleName %>.wasm

  publish:
    name: Push released module to OCI registry
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Install wasm-to-oci
      run: |
        mkdir tools
        wget https://github.com/engineerd/wasm-to-oci/releases/download/v0.1.1/linux-amd64-wasm-to-oci -q -O ./tools/wasm-to-oci
        chmod +x ./tools/wasm-to-oci

    - name: Set the release version
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Set the release version
      if: github.ref == 'refs/heads/main'
      run: echo "RELEASE_VERSION=canary" >> $GITHUB_ENV

    - name: Download release assets
      uses: actions/download-artifact@v1
      with:
        name: <%= moduleName %>.wasm
        path: ./assets

    # TODO: FILL IN THE << ... >> bit below

    # - name: Log into registry
    #   run: << your docker login equivalent here >>

    # - name: Publish to registry
    #   run: ./tools/wasm-to-oci push ./assets/<%= moduleName %>.wasm << your OCI reference here e.g. myname.myprovider.io/<%= moduleName %>:${RELEASE_VERSION} >>
